POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Phatv2",
    "password": "Phat1234",
    "email":"Pvphat12c6ntt@gmail.com",
    "NumberPhone":"0937175474"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "Phatv2",
    "password": "Phat1234"
}

###
POST http://localhost:5000/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhMmMzY2IyZTNkMTI0OThkMWE0ODciLCJpYXQiOjE2Mjk5NjI2NTV9.dH6bmxYoTFSxOkVkkyl1p0K5C_lVWQW3YxgEWlYxuvg

{
        "title": "Mobile",
        "content": "mobile",
        "author": "PHP",
        "url": "https://github.com/daipham3213/BeHealthy",
        "likeCount" : 0
}

###
GET http://localhost:5000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhMjU4MGJkN2I1NjIwNzRiYzkxMmQiLCJpYXQiOjE2Mjk5NjI1OTh9.JwhfBplwvw_gvXVZ49TpegyvSqSWQyTsTVzbwB-9was

###
GET http://localhost:5000/api/posts/about
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhMjU4MGJkN2I1NjIwNzRiYzkxMmQiLCJpYXQiOjE2Mjk5NjI1OTh9.JwhfBplwvw_gvXVZ49TpegyvSqSWQyTsTVzbwB-9was


###
PUT http://localhost:5000/api/posts/611a2c3cb2e3d12498d1a487
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhMmMzY2IyZTNkMTI0OThkMWE0ODciLCJpYXQiOjE2MjkxMTY1MjJ9.hFjb2FoMWhwbBvHCUSSKoAI8KzQpY-sugBe_6X3EsCY

{
    "title": "my first post1309",
    "content": "phathasha",
    "author": "phatvpdd",
     "url": "https://github.com/"    
}

###
PUT http://localhost:5000/api/auth/editUser/611a2c3cb2e3d12498d1a487
Content-Type: application/json

{
    "username": "Phatvs2", 
    "password": "$argon2i$v=19$m=4096,t=3,p=1$oEvpHYqw8840aX9p2y4L2g$kx1XeCGEl8VQK7uTEkFnR0YUJJuATcJLeH21lyQ+8iY", 
    "email":"huyhuyhguy@gmail.com", 
    "NumberPhone": "025369874"   
}

###
DELETE http://localhost:5000/api/posts/61239621f492ae27344220a5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTFhMmMzY2IyZTNkMTI0OThkMWE0ODciLCJpYXQiOjE2MjkxMTY1MjJ9.hFjb2FoMWhwbBvHCUSSKoAI8KzQpY-sugBe_6X3EsCY



